---------------------------------------------------------------------------------------------------------
---- INSERT, UPDATE Y DELETE
---------------------------------------------------------------------------------------------------------
/* QUERY 69:AUMENTAR UN 20% EL PRECIO DE LISTA DE TODOS LOS PRODUCTOS  */
UPDATE [Production].[Product]
SET [ListPrice] = [ListPrice]  * 1.2


/* QUERY 70:AUMENTAR UN 20% EL PRECIO DE LISTA DE LOS PRODUCTOS DEL PROVEEDOR 1540 */
UPDATE [Production].[Product] AS P
SET [ListPrice] = [ListPrice]  * 1.2
INNER JOIN 

/* QUERY 71:AGREGAR UN DIA DE VACACIONES A LOS 10 EMPLEADOS CON MAYOR ANTIGUEDAD.*/


/* QUERY 72: ELIMINAR LOS DETALLES DE COMPRA (PURCHASEORDERDETAIL) CUYAS FECHAS DE 
VENCIMIENTO PERTENEZCAN AL TERCER TRIMESTRE DEL AÑO 2006 */

/* QUERY 73:QUITAR REGISTROS DE LA TABLA SALESPERSONQUOTAHISTORY CUANDO LAS VENTAS DEL AÑO HASTA LA FECHA 
--ALMACENADAS EN LA TABLA SALESPERSON SUPERE EL VALOR DE 2500000*/


---------------------------------------------------------------------------------------------------------
---- BULK COPY
--------------------------------------------------------------------------------------------------------

/* QUERY 74: CLONAR ESTRUCTURA Y DATOS DE LOS CAMPOS NOMBRE ,COLOR Y PRECIO DE LISTA 
DE LA TABLA PRODUCTION.PRODUCT EN UNA TABLA LLAMADA PRODUCTOS */


/* QUERY 75: CLONAR SOLO ESTRUCTURA DE LOS CAMPOS IDENTIFICADOR ,NOMBRE Y 
APELLIDO DE LA TABLA PERSON.PERSON EN UNA TABLA LLAMADA PRODUCTOS */


/* QUERY 76:INSERTAR UN PRODUCTO DENTRO DE LA TABLA PRODUCTOS.TENER EN CUENTA LOS SIGUIENTES 
DATOS: EL COLOR DE PRODUCTO DEBE SER ROJO, EL NOMBRE DEBE SER "BICICLETA MOUNTAIN BIKE" 
Y EL PRECIO DE LISTA DEBE SER DE 4000 PESOS.*/

/* QUERY 77: COPIAR LOS REGISTROS DE LA TABLA PERSON.PERSON A LA TABLA PERSONAS CUYO 
IDENTIFICADOR ESTE ENTRE 100 Y 200 */

/* QUERY 78: AUMENTAR EN UN 15% EL PRECIO DE LOS PEDALES DE BICICLETA */


 /* QUERY 79: ELIMINAR DE LAS PERSONAS CUYO NOMBRE EMPIECEN CON LA LETRA M*/


 /* QUERY 80: BORRAR TODO EL CONTENIDO DE LA TABLA PRODUCTOS */

 /* QUERY 81: BORRAR TODO EL CONTENIDO DE LA TABLA PERSONAS SIN UTILIZAR LA INSTRUCCIÓN DELETE.*/